name: workshop-compose

services:

  app:
    container_name: app
    build: ./app
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
    networks:
      - app_net

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: user-password
    ports:
      - 3306:3306
    networks:
      - app_net

networks:
  app_net: {}

